development:
    #tsunai-setteings
    webhost: "https://google-mythings-yumikotsunai.c9users.io/"
    connect:
        user_name: "demo@remotelock.com"
        client: "ae37f4e8e41781ec4f61924a67f0ad85fcfd50ffbc779ca0c1e06217bbeff35e"
        secret: "38214d9cbf939ae7ffef20428c994d42eae65d7c5c47a04f4af1e82aaee03af9"
    google:
        #user_name: "yumikokke@gmail.com"
        user_name: "A"
        client: "841258018012-jqn06q4ifmfvbj5ip42rvtemetcga7oj.apps.googleusercontent.com"
        secret: "HuQ43i5_NiqOeOIZca4oJttJ"
        calendar_id: "i8a77r26f9pu967g3pqpubv0ng@group.calendar.google.com"
        google-site-verification: '<meta name="google-site-verification" content="yXHeDhmd4GXL3-G-H0JweJuPZspzF_8IPRkmmBqC2Iw" />'
    
#APP_CONFIG["connect"]["client"]
    
production:
    webhost: "https://mythingsdemo.herokuapp.com/"
    connect:
        user_name: "demo@remotelock.com"
        client: "86169dfc79da7ce9000a1d2f37dcb95f96d9b3bb03bf32e57b540cbaedbf0989"
        secret: "1bfa525b96c3102c65d1f2be4abfa541f0b57ee17ac92dffbb9abf6417740c23"
        uuid: "8a2f4c49-1c3a-41e4-bfa8-8dcde063ee07"
    google:
        user_name: "kke.remotelock@gmail.com"
        client: "404180661728-qotv9so92qt4pp6s7v9jlmheik6bespe.apps.googleusercontent.com"
        secret: "_ZS6_pVing3DInTzpJ7c3QpJ"
        calendar_id: "g8ukpibvlfle41hplt1g3rplu0@group.calendar.google.com"
        #google-site-verification: '<meta name="google-site-verification" content="mwXIsAM7T9kSRBW3kjGPEP7LkI_CATVt0eJgBTmK-es" />'
        #↑apidemo2 ↓apidemo
        google-site-verification: '<meta name="google-site-verification" content="PZDi1CWGW25rzFiv5I5OBN2btplsGK2ErW3jxVZ8DsQ" />'
